[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "test_pckage"
version = "0.1.0"
description = "Internal tools for Menteru data processing"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]
